#### Deel twee van de fruittelere analyse. 

In dit deel zullen we kijken naar hoeveel de tuinder zelf heeft geproduceert zodat we dat kunnen beter kunnen kwantificeren adhv dynamische prijzen.

In [1]:
import pandas as pd
import openpyxl

In [2]:
df = pd.read_excel('Productie_kwartierdata_2023.xlsx', skiprows=[0])
df

,Datum-tijd tot,Elektriciteit Productie (kWh),Blindverbruik Productie (kVARh),Elektriciteit Productie (kWh).1,Blindverbruik Productie (kVARh).1,Elektriciteit Productie (kWh).2,Blindverbruik Productie (kVARh).2
0,2023-01-01 00:15:00,0.0,0.0,0.0,0.3,NaN,NaN
1,2023-01-01 00:30:00,0.0,0.0,0.0,0.3,NaN,NaN
2,2023-01-01 00:45:00,0.0,0.0,0.0,0.3,NaN,NaN
3,2023-01-01 01:00:00,0.0,0.0,0.0,0.3,NaN,NaN
4,2023-01-01 01:15:00,0.0,0.0,0.0,0.3,NaN,NaN
...,...,...,...,...,...,...,...
35036,2023-12-31 23:15:00,0.0,0.0,0.0,0.3,0.0,0.5
35037,2023-12-31 23:30:00,0.0,0.0,0.0,0.3,0.0,0.4
35038,2023-12-31 23:45:00,0.0,0.0,0.0,0.3,0.0,0.5
35039,2024-01-01 00:00:00,0.1,0.0,0.1,0.3,0.0,0.5
35040,2024-01-01 00:00:00,0.1,NaN,NaN,NaN,NaN,NaN

In [3]:
nan_df = df.isna()
df_clean = df.fillna(0)
df_clean

#factor to multiply the kVARH columns with is 0.8 so:
columns_to_multiply = ['Blindverbruik Productie (kVARh)', 'Blindverbruik Productie (kVARh).1','Blindverbruik Productie (kVARh).2']
factor = 0.8

kwh_df = df_clean

for column in columns_to_multiply:
    kwh_df[column] = kwh_df[column] * factor

kwh_df

,Datum-tijd tot,Elektriciteit Productie (kWh),Blindverbruik Productie (kVARh),Elektriciteit Productie (kWh).1,Blindverbruik Productie (kVARh).1,Elektriciteit Productie (kWh).2,Blindverbruik Productie (kVARh).2
0,2023-01-01 00:15:00,0.0,0.0,0.0,0.24,0.0,0.00
1,2023-01-01 00:30:00,0.0,0.0,0.0,0.24,0.0,0.00
2,2023-01-01 00:45:00,0.0,0.0,0.0,0.24,0.0,0.00
3,2023-01-01 01:00:00,0.0,0.0,0.0,0.24,0.0,0.00
4,2023-01-01 01:15:00,0.0,0.0,0.0,0.24,0.0,0.00
...,...,...,...,...,...,...,...
35036,2023-12-31 23:15:00,0.0,0.0,0.0,0.24,0.0,0.40
35037,2023-12-31 23:30:00,0.0,0.0,0.0,0.24,0.0,0.32
35038,2023-12-31 23:45:00,0.0,0.0,0.0,0.24,0.0,0.40
35039,2024-01-01 00:00:00,0.1,0.0,0.1,0.24,0.0,0.40
35040,2024-01-01 00:00:00,0.1,0.0,0.0,0.00,0.0,0.00

In [4]:
#Optellen van het vebruik zodat het duidelijk is of de ramingen van ray eenigzins overeenkomen met de aangeleverde data.

Total_consumptie1 = kwh_df['Elektriciteit Productie (kWh)'].sum()
Total_consumptie2 = kwh_df['Elektriciteit Productie (kWh).1'].sum()
Total_consumptie3 = kwh_df['Elektriciteit Productie (kWh).2'].sum()

Total_kVARH1 =  kwh_df['Blindverbruik Productie (kVARh)'].sum()
Total_kVARH2 =  kwh_df['Blindverbruik Productie (kVARh).1'].sum()
Total_kVARH3 =  kwh_df['Blindverbruik Productie (kVARh).2'].sum()

print(Total_consumptie1)
print(Total_consumptie2)
print(Total_consumptie3)
print(Total_kVARH1)
print(Total_kVARH2)
print(Total_kVARH3)

Totaal_kwh = (Total_consumptie1 + Total_consumptie2 + Total_consumptie3 + Total_kVARH1 + Total_kVARH2 + Total_kVARH3)
print(f'Totaal aan kwh: {Totaal_kwh}')

392871.255
237829.176
230863.388
0.4000000000000001
4337.040000000001
2996.7200000000003
Totaal aan kwh: 868897.979

In [5]:
kwh_df['Datum-tijd tot'] = pd.to_datetime(kwh_df['Datum-tijd tot'], format='%d-%m-%Y %H:%M')

# Voeg een nieuwe kolom toe met de afgeronde tijden naar het dichtstbijzijnde uur
kwh_df['Datum-tijd uur'] = kwh_df['Datum-tijd tot'].dt.ceil('H')

kwh_df_hourly = kwh_df.groupby('Datum-tijd uur').agg({
    
    'Elektriciteit Productie (kWh)': 'sum',
    'Blindverbruik Productie (kVARh)': 'sum',
    'Elektriciteit Productie (kWh).1': 'sum',
    'Blindverbruik Productie (kVARh).1': 'sum',
    'Elektriciteit Productie (kWh).2': 'sum',
    'Blindverbruik Productie (kVARh).2': 'sum'

    }).reset_index()


kwh_df_hourly.rename(columns={'Datum-tijd uur' : 'StartDate'}, inplace=True)

# Toon het resulterende DataFrame
kwh_df_hourly

,StartDate,Elektriciteit Productie (kWh),Blindverbruik Productie (kVARh),Elektriciteit Productie (kWh).1,Blindverbruik Productie (kVARh).1,Elektriciteit Productie (kWh).2,Blindverbruik Productie (kVARh).2
0,2023-01-01 01:00:00,0.0,0.0,0.0,0.96,0.0,0.00
1,2023-01-01 02:00:00,0.0,0.0,0.0,1.04,0.0,0.00
2,2023-01-01 03:00:00,0.0,0.0,0.0,0.96,0.0,0.00
3,2023-01-01 04:00:00,0.0,0.0,0.0,1.04,0.0,0.00
4,2023-01-01 05:00:00,0.0,0.0,0.0,1.04,0.0,0.00
...,...,...,...,...,...,...,...
8755,2023-12-31 20:00:00,0.0,0.0,0.0,0.96,0.0,1.44
8756,2023-12-31 21:00:00,0.0,0.0,0.0,0.96,0.0,1.52
8757,2023-12-31 22:00:00,0.0,0.0,0.0,0.96,0.0,1.44
8758,2023-12-31 23:00:00,0.0,0.0,0.0,1.04,0.0,1.36
8759,2024-01-01 00:00:00,0.2,0.0,0.1,0.96,0.0,1.52

In [6]:
mp = pd.read_csv('marktprijzen_2023.csv')

mp["StartDate"] = mp["StartDate"].astype("datetime64[ns]")

In [7]:
# nu gaan we door naar de grote df join show

full_df = kwh_df_hourly.join(mp, how='inner', lsuffix='kwh_df_hourly', rsuffix='mp')

full_df = full_df.drop('StartDatemp', axis=1)

full_df

,StartDatekwh_df_hourly,Elektriciteit Productie (kWh),Blindverbruik Productie (kVARh),Elektriciteit Productie (kWh).1,Blindverbruik Productie (kVARh).1,Elektriciteit Productie (kWh).2,Blindverbruik Productie (kVARh).2,Price_kWh
0,2023-01-01 01:00:00,0.0,0.0,0.0,0.96,0.0,0.00,-0.00146
1,2023-01-01 02:00:00,0.0,0.0,0.0,1.04,0.0,0.00,-0.00152
2,2023-01-01 03:00:00,0.0,0.0,0.0,0.96,0.0,0.00,-0.00500
3,2023-01-01 04:00:00,0.0,0.0,0.0,1.04,0.0,0.00,-0.00460
4,2023-01-01 05:00:00,0.0,0.0,0.0,1.04,0.0,0.00,-0.00405
...,...,...,...,...,...,...,...,...
8755,2023-12-31 20:00:00,0.0,0.0,0.0,0.96,0.0,1.44,0.03489
8756,2023-12-31 21:00:00,0.0,0.0,0.0,0.96,0.0,1.52,0.01330
8757,2023-12-31 22:00:00,0.0,0.0,0.0,0.96,0.0,1.44,0.01068
8758,2023-12-31 23:00:00,0.0,0.0,0.0,1.04,0.0,1.36,0.00317
8759,2024-01-01 00:00:00,0.2,0.0,0.1,0.96,0.0,1.52,0.00010

In [8]:
# dan gaan we nu door naar het berkenene van de prijzen van de consumptie


price_df = full_df[['Elektriciteit Productie (kWh)', 'Blindverbruik Productie (kVARh)', 'Elektriciteit Productie (kWh).1', 'Blindverbruik Productie (kVARh).1', 'Elektriciteit Productie (kWh).2', 'Blindverbruik Productie (kVARh).2']].multiply(full_df["Price_kWh"], axis="index")
price_df['StartDatekwh_df_hourly'] = full_df['StartDatekwh_df_hourly']

first_column = price_df.pop('StartDatekwh_df_hourly')
price_df.insert(0, 'StartDatekwh_df_hourly', first_column)


price_df

,StartDatekwh_df_hourly,Elektriciteit Productie (kWh),Blindverbruik Productie (kVARh),Elektriciteit Productie (kWh).1,Blindverbruik Productie (kVARh).1,Elektriciteit Productie (kWh).2,Blindverbruik Productie (kVARh).2
0,2023-01-01 01:00:00,-0.00000,-0.0,-0.00000,-0.001402,-0.0,-0.000000
1,2023-01-01 02:00:00,-0.00000,-0.0,-0.00000,-0.001581,-0.0,-0.000000
2,2023-01-01 03:00:00,-0.00000,-0.0,-0.00000,-0.004800,-0.0,-0.000000
3,2023-01-01 04:00:00,-0.00000,-0.0,-0.00000,-0.004784,-0.0,-0.000000
4,2023-01-01 05:00:00,-0.00000,-0.0,-0.00000,-0.004212,-0.0,-0.000000
...,...,...,...,...,...,...,...
8755,2023-12-31 20:00:00,0.00000,0.0,0.00000,0.033494,0.0,0.050242
8756,2023-12-31 21:00:00,0.00000,0.0,0.00000,0.012768,0.0,0.020216
8757,2023-12-31 22:00:00,0.00000,0.0,0.00000,0.010253,0.0,0.015379
8758,2023-12-31 23:00:00,0.00000,0.0,0.00000,0.003297,0.0,0.004311
8759,2024-01-01 00:00:00,0.00002,0.0,0.00001,0.000096,0.0,0.000152

Onbalanskosten voor een GV hiervoor nemen we:

Terugleveringopslag	1-5-2024 tot onbekend	
Onbalanskosten enkel (teruglevering):
â‚¬ -0,010260 per kWh


en Totaal_kwh om verder met te rekenen.

In [12]:
kosten_onbalans = Totaal_kwh *  -0.010260
kosten_onbalans

-8914.89326454

In [16]:
#sommeren van de columns om tataal te krijgen. 
Total_consumptie1 = price_df['Elektriciteit Productie (kWh)'].sum()
Total_consumptie2 = price_df['Elektriciteit Productie (kWh).1'].sum()
Total_consumptie3 = price_df['Elektriciteit Productie (kWh).2'].sum()

Total_kVARH1 =  price_df['Blindverbruik Productie (kVARh)'].sum()
Total_kVARH2 =  price_df['Blindverbruik Productie (kVARh).1'].sum()
Total_kVARH3 =  price_df['Blindverbruik Productie (kVARh).2'].sum()

#print(Total_consumptie1)
#print(Total_consumptie2)
#print(Total_consumptie3)
#print(Total_kVARH1)
#print(Total_kVARH2)
#print(Total_kVARH3)

prijs_totaal = (Total_consumptie1 + Total_consumptie2 + Total_consumptie3 + Total_kVARH1 + Total_kVARH2 + Total_kVARH3)

prijs_round = prijs_totaal.round(2)
opslag = kosten_onbalans.round(2)

oplevering = prijs_round + opslag

print(f'In het jaar 2023 met een marktprijscontract zou er voor: â‚¬ {oplevering} aan teruglevering via Prodcutie zijn geweest')

In het jaar 2023 met een marktprijscontract zou er voor: â‚¬ 50208.21 aan teruglevering via Prodcutie zijn geweest